### ISSUE TITLE
remove dependency on Distributions.jl

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPToolbox.jl#10]
Distributions.jl does not support rng specification. For this reason, I don't think we should use it right now. I think we can have our own implementations of important things like a categorical distribution in POMDPToolbox for now.

**Comment by etotheipluspi** [comment]
That's fine. I can implement a categorical distribution in line with what's in Distriubtions.jl. Are there any other distributions we should think of supporting as well?

**Comment by cho3** [comment]
Should we add support for `WeightVec` and `sample` from StatsBase? Although that might just be subsumed by the categorical distribution. Curently that version of sample doesn't have rng support.

**Comment by zsunberg** [comment]
If we want, we could actually use the data structures from Distributions
and StatsBase actually and just write our own versions of rand and sample

**Comment by etotheipluspi** [comment]
I was thinking of what @zsunberg is proposing. This is what I did in POMDPDistributions.

**Comment by etotheipluspi** [comment]
Tagged with summer of code. Anyone working on this, can check out this [repo](https://github.com/JuliaPOMDP/POMDPDistributions.jl).

**Comment by zsunberg** [comment]
@etotheipluspi , can you get rid of model/initial.jl? That seems to be the only remaning dependency on Distributions.jl

Also, I added a way to sample from a WeightVec with a supplied rng (@e0def2f). This could be used wherever we have categorical distributions.
