### ISSUE TITLE
Simulation histories should (optionally) contain rng snapshots at each step.

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPToolbox.jl#24]
so that everything is super-reproducible

**Comment by mykelk** [comment]
I think it is up to the person recording the history to take their own snapshot.

**Comment by zsunberg** [comment]
@mykelk sorry I didn't make the context clear. This is for the specific HistoryRecorder that I have implemented in POMDPToolbox. There is no standard interface or anything for recording histories

**Comment by mykelk** [comment]
Ah, got it.

**Comment by zsunberg** [comment]
Now a person can do this by saving a copy of the rng in the info, so I don't think this is necessary.
