### ISSUE TITLE
rename History

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPToolbox.jl#28]
Maybe History is not the right word for a record of a simulation. Maybe it should be Trajectory or Episode?

**Comment by mykelk** [comment]
Trajectory feels like it is restricted to just state or state-action sequences. I think I'm okay with History or Episode.

**Comment by zsunberg** [comment]
Another thing to consider: Reinforce.jl already exports an Episode class

**Comment by rejuvyesh** [comment]
Common variable names I've seen include `path`, `episode` and `trajectory` but not `history`.

**Comment by zsunberg** [comment]
I think I like `Episode` the best - only problem is that it clashes with Reinforce.jl (it basically means the same thing though). Do we care about that clash?

**Comment by zsunberg** [comment]
I guess there actually won't be anything named only `Episode`, there will be `AbstractEpisode` `AbstractPOMDPEpisode`, `POMDPEpisode`, etc., so there will be no clash.

Is it worth it to rename? (Ugh... naming is hard)

**Comment by mykelk** [comment]
Up to you.

**Comment by zsunberg** [comment]
I don't think it's worth it to do this
