### ISSUE TITLE
History interface

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPToolbox.jl#29]
The current interface to history objects is not obvious. How do we make it easier to understand?

**Comment by zsunberg** [comment]
working on an interface that would look like this (`hist` is a SimHistory)

```julia
for (s, r, sp) in iterator(hist, "(s, r, sp)")
    println("received reward $r when transitioning from $s to $sp")
end
```
or
```julia
for (a, o) in iterator(hist, "ao")
    println("action: $a")
    println("obs: $o")
end
```
or
```julia
aotuples = collect(iterator(hist, (:a,:o)))
```
Any comments? @ekhlassonu

**Comment by zsunberg** [comment]
Actually I like `eachstep` rather than `iterator` for the name of this function. @mykelk, @MaximeBouton, @etotheipluspi votes?

**Comment by mykelk** [comment]
Eachstep is probably nicer.

**Comment by zsunberg** [comment]
Also, should it always return tuples, or should it return individual items if only one thing is specified?

i.e. in
```julia
for r in eachstep(h, "r")
```
should `r` be a `Float64`, or should it be a `Tuple{Float64}`? I think just a `Float64`.

**Comment by zsunberg** [comment]
This is what I'm currently doing regarding single argument versions:
- `eachstep(h, :r)` returns `Float64`s
- `eachstep(h, (:r,)) returns `Tuple{Float64}`s
- `eachstep(h, "r") returns `Float64`s

**Comment by mykelk** [comment]
I think that's good.
