### ISSUE TITLE
Printing output during simulation

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPToolbox.jl#31]
One thing that we don't have right now is a way to print output *during* a simulation like this*:

![C++ DESPOT output gif](https://cloud.githubusercontent.com/assets/4240491/26809500/2b3a49cc-4a1a-11e7-83b1-6908afb6040b.gif)

As of now, the only way to do this is to write your own simulator (scary because it may not behave the same as other POMDPs.jl simulators) or to put print statements in your problem definition (bad because it will also print when being used by a solver).

One convenient syntax for making this printing possible is to have an iterator that iterates through steps *as it is simulating*, similar to the [Episode](https://github.com/JuliaML/Reinforce.jl/blob/master/src/episodes/iterators.jl) from Reinforce.jl. An example usage would look like this:

```julia
for (s, a, sp, o) in stepthrough(pomdp, policy, "saspo")
     println("reached state $sp and generated observation $o after taking action $a in state $s")
end
```

You could of course do something besides printing, like saving, learning, analyzing, etc. What do people think?

Another issue is what the syntax should be, some options are
1. `for _ in simulate(StepSimulator(), pomdp, policy)`
2. `for _ in eachstep(simulate(StepSimulator(), pomdp, policy)`
3. `for _ in step_through_sim(pomdp, policy)`
4. `for _ in Episode(pomdp, policy)` (this clashes with Reinforce.jl - or maybe we should use their code)

I think I like 1 with `stepthrough` as a convenience function.

* Note: the `sim` function suffices for this in the MDP case because there is no state uncertainty so everything is available in the policy callback function, but it does not suffice in the POMDP case.

**Comment by mykelk** [comment]
I like 1 best as well.
