### ISSUE TITLE
Delta distribution

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPToolbox.jl#37]
it would be handy to have a distribution for cases when next states or observations are deterministic - a distribution that can represent the Kronecker delta or Dirac delta distribution functions. Is `DeltaDistribution` or `KroneckerDelta` (and `DiracDelta`?) the best name?

**Comment by mykelk** [comment]
Kronecker isn't the same as the Dirac delta. I think you want Dirac or Deterministic. Include Distribution in the name if that's the convention in the package.

**Comment by zsunberg** [comment]
Isn't Kronecker is the correct distribution to use if the state space is discrete? I'm saying we may want to have two: `KroneckerDelta` and `DiracDelta`, where
```julia
pdf(d::KroneckerDelta, x) = x == d.x ? 1.0 : 0.0
```
I'm not sure how pdf for the Dirac one should be defined though - would we have it return `Inf`?

**Comment by mykelk** [comment]
Yes, that's the right one if it's discrete. Yeah, I think you can return `Inf`.

**Comment by zsunberg** [comment]
I closed this when SparseCat was created, but now it makes a lot more sense to have with the small union optimizations

**Comment by zsunberg** [comment]
I like the name Deterministic better now
