### ISSUE TITLE
`run_parallel` not finding definitions

### ISSUE THREAD

**Issue by bisraelsen** [JuliaPOMDP/POMDPToolbox.jl#51]
I'm trying to run several simulations in parallel, and using the example in the `README` as a guide. I keep getting this error and am having a difficult time troubleshooting it. All of these functions **are** implemented and the code works fine when I run it in serial.

```julia
From worker 3:  WARNING: POMDPs.jl: Could not find or synthesize generate_sr(::roadnet_with_pursuer, ::roadnet_pursuer_state, ::Symbol, ::MersenneTwister). Either implement it directly, or, to automatically synthesize it, implement the following methods from the explicit interface:
From worker 3:
From worker 3:    [X] transition(::roadnet_with_pursuer, ::roadnet_pursuer_state, ::Symbol)
From worker 3:    [X] reward(::roadnet_with_pursuer, ::roadnet_pursuer_state, ::Symbol, ::roadnet_pursuer_state)
From worker 3:
From worker 3:
From worker 3:  OR implement the following methods from the generative interface:
From worker 3:
From worker 3:    [X] generate_s(::roadnet_with_pursuer, ::roadnet_pursuer_state, ::Symbol, ::AbstractRNG)
From worker 3:    [X] reward(::roadnet_with_pursuer, ::roadnet_pursuer_state, ::Symbol, 
 :roadnet_pursuer_state)
From worker 3:
From worker 3:
From worker 3:  ([✔] = already implemented correctly; [X] = missing)
```

I have included `@everywhere` when I use the `POMDPs` and `POMDPToolbox` packages. I am also importing my custom MDP definitions via an `@everywhere include("my_definitions")` command.... could that be the problem?

**Comment by zsunberg** [comment]
my first guess: you're not explicitly importing the methods from POMDPs in my_definitions.jl

Will write back with some more later

**Comment by zsunberg** [comment]
Yep after trying a few more things, I think you need to use `importall POMDPs` in my_definitions instead of `using POMDPs`

**Comment by zsunberg** [comment]
Let me know if that doesn't fix it.

**Comment by bisraelsen** [comment]
Yeah, the `importall` piece was necessary, but it gets pretty complicated depending on the structure of the code. I had to dive a bit deeper into namespacing and workers.

Thanks!
