### ISSUE TITLE
Maybe this package should be archived or readme modified to show it's deprecated

### ISSUE THREAD

**Issue by BoZenKhaa** [JuliaPOMDP/POMDPToolbox.jl#79]
If I understand correctly, it was superseded by a collection of packages described in README, later superseded by a https://github.com/JuliaPOMDP/POMDPs.jl/tree/master/lib/POMDPTools

This repo came up when I was googling a function I was unsure which package it was implemented in.

**Comment by zsunberg** [comment]
I just updated the README and will archive the package shortly.
